"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createMutationFn = exports.createQueryFn = exports.setAxiosInstance = exports.makeTypedFormData = void 0;
var TypedFormData_1 = require("./TypedFormData");
Object.defineProperty(exports, "makeTypedFormData", { enumerable: true, get: function () { return TypedFormData_1.makeTypedFormData; } });
var axios_1 = require("./axios");
Object.defineProperty(exports, "setAxiosInstance", { enumerable: true, get: function () { return axios_1.setAxiosInstance; } });
var createQueryFn_1 = require("./createQueryFn");
Object.defineProperty(exports, "createQueryFn", { enumerable: true, get: function () { return createQueryFn_1.createQueryFn; } });
var createMutationFn_1 = require("./createMutationFn");
Object.defineProperty(exports, "createMutationFn", { enumerable: true, get: function () { return createMutationFn_1.createMutationFn; } });
